[package]
name = "passutil"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
pwhash = "1.0.0"
random_word = { version = "0.5.0", features = ["en", "es", "fr", "ja", "zh", "de"] }
rpassword = "7.3.1"
passwords = "3.1.16"
