[package]
name = "passutil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
pwhash = "1.0.0"
random_word = { version = "0.4.3", features = ["en", "es", "fr", "ja", "zh", "de"] }
rand = "0.8.5"
rpassword = "7.3.1"
