name: Build the passutil binary

on:
  # Trigger the workflow on push and pull request events
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.83.0

      # Build the binary
      - name: Build for ${{ matrix.os }}
        run: cargo build --release

      - name: Run tests
        run: cargo test

      # Rename the binary to include the OS name and architecture
      - name: Rename binary
        run: |
          mkdir -p output
          OS=$(uname -o | tr A-Z a-z)
          ARCH=$(uname -m)
          TARGET=$(printf "%s-%s" $OS $ARCH)
          cp target/release/passutil output/passutil-$TARGET

      # Upload the binaries as an artifact
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: output/