name: Build the passutil binary

on:
  # Trigger the workflow on push and pull request events
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.83.0

      # Build the binary
      - name: Build for ${{ matrix.os }}
        run: cargo build --release

      # Run tests
      - name: Run tests
        run: cargo test

      # Rename the binary to include the OS name and architecture
      - name: Rename binary
        if: startsWith(github.ref_name, 'v')
        run: |
          mkdir -p output
          OS=$(uname -s | tr A-Z a-z)
          ARCH=$(uname -m)
          TARGET=$(printf "%s-%s" $OS $ARCH)
          VERSION=$(target/release/passutil -V | awk '{print $2}')
          cp target/release/passutil output/passutil-${VERSION}-${TARGET}

      # Upload the binaries as an artifact
      - name: Upload binaries
        if: startsWith(github.ref_name, 'v')
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: output/
